//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntity
{
    using System;
    using System.Collections.Generic;

    public class CampoPlantilla : Entity
    {
        public CampoPlantilla()
        {
            this.Campo = new HashSet<Campo>();
        }
    
        public string Nombre { get; set; }
        public int Longitud { get; set; }
        public bool Selector { get; set; }
        public bool Variable { get; set; }
        public bool ProtegidoLog { get; set; }
        public bool Almacenado { get; set; }
        public int GrupoMensajeId { get; set; }
        public int TipoDatoId { get; set; }
        public int PosicionRelativa { get; set; }
        public Nullable<int> LongitudCabecera { get; set; }
        public bool Cabecera { get; set; }
        public bool Bitmap { get; set; }
        public bool Transaccional { get; set; }
    
        public virtual ICollection<Campo> Campo { get; set; }
        public virtual GrupoMensaje GrupoMensaje { get; set; }
        public virtual TipoDato TipoDato { get; set; }
    }
}
