//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntity
{
    using System;
    using System.Collections.Generic;

    public class Columna : Entity
    {
        public string Nombre { get; set; }
        public int Longitud { get; set; }
        public int TablaId { get; set; }
        public int TipoDatoColumnaId { get; set; }

        public virtual Tabla Tabla { get; set; }
        public virtual TipoDatoColumna TipoDatoColumna { get; set; }
    }
}
