
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>


namespace BusinessEntity
{
    using System;

    public class CriptografiaCampo : Entity
    {
        public int DinamicaCriptografiaId { get; set; }
        public int CampoResultadoId { get; set; }
        public int MensajeResultadoId { get; set; }
        public Nullable<int> CampoLlave1Id { get; set; }
        public Nullable<int> MensajeLlave1Id { get; set; }
        public Nullable<int> CampoLlave2Id { get; set; }
        public Nullable<int> MensajeLlave2Id { get; set; }
        public string Llave1 { get; set; }
        public string Llave2 { get; set; }
        public int TipoLlave1 { get; set; }
        public Nullable<int> TipoLlave2 { get; set; }
        public bool SegundaLlave { get; set; }
        public Nullable<int> OperacionLlave { get; set; }
        public int Algoritmo { get; set; }

        public virtual DinamicaCriptografia DinamicaCriptografia { get; set; }
    }
}
