
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>


namespace BusinessEntity
{
    using System;
    using System.Collections.Generic;

    public class EntidadComunicacion : Entity
    {
        public EntidadComunicacion()
        {
            this.PasosDinamica = new HashSet<PasoDinamica>();
            this.Terminales = new HashSet<Terminal>();
        }

        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string RutaLog { get; set; }
        public string NombreLog { get; set; }
        public Nullable<int> ProtocoloId { get; set; }
        public Nullable<int> TimeoutCola { get; set; }
        public Nullable<int> GrupoMensajeId { get; set; }
        public Nullable<int> TipoEntidadId { get; set; }
        public string Cola { get; set; }

        public virtual Protocolo Protocolo { get; set; }
        public virtual TipoEntidad TipoEntidad { get; set; }
        public virtual GrupoMensaje GrupoMensaje { get; set; }
        public virtual ICollection<PasoDinamica> PasosDinamica { get; set; }
        public virtual ICollection<Terminal> Terminales { get; set; }
    }
}
