//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntidadComunicacion
    {
        public EntidadComunicacion()
        {
            this.PasoDinamica = new HashSet<PasoDinamica>();
            this.Terminal = new HashSet<Terminal>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public string RutaLog { get; set; }
        public string NombreLog { get; set; }
        public Nullable<int> ProtocoloId { get; set; }
        public Nullable<int> TimeoutCola { get; set; }
        public Nullable<int> GrupoMensajeId { get; set; }
        public Nullable<int> TipoEntidadId { get; set; }
        public string Cola { get; set; }
    
        public virtual Protocolo Protocolo { get; set; }
        public virtual TipoEntidad TipoEntidad { get; set; }
        public virtual GrupoMensaje GrupoMensaje { get; set; }
        public virtual ICollection<PasoDinamica> PasoDinamica { get; set; }
        public virtual ICollection<Terminal> Terminal { get; set; }
    }
}
