
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>


namespace BusinessEntity
{
    public class FuncionUsuario:Entity
    {
        public int UsuarioId { get; set; }
        public double FuncionId { get; set; }
    }
}
