
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>


namespace BusinessEntity
{
    using System;
    using System.Collections.Generic;

    public class Mensaje : Entity
    {
        public Mensaje()
        {
            this.Campo = new HashSet<Campo>();
            this.DinamicaCriptografia = new HashSet<DinamicaCriptografia>();
            this.GrupoValidacion = new HashSet<GrupoValidacion>();
            this.MensajeTransaccional = new HashSet<MensajeTransaccional>();
            this.Transformacion = new HashSet<Transformacion>();
            this.Transformacion1 = new HashSet<Transformacion>();
        }

        public string Nombre { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> GrupoMensajeId { get; set; }

        public virtual ICollection<Campo> Campo { get; set; }
        public virtual ICollection<DinamicaCriptografia> DinamicaCriptografia { get; set; }
        public virtual GrupoMensaje GrupoMensaje { get; set; }
        public virtual ICollection<GrupoValidacion> GrupoValidacion { get; set; }
        public virtual ICollection<MensajeTransaccional> MensajeTransaccional { get; set; }
        public virtual ICollection<Transformacion> Transformacion { get; set; }
        public virtual ICollection<Transformacion> Transformacion1 { get; set; }
    }
}
