
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>


namespace BusinessEntity
{
    using System;

    public class ParametroTransformacionCampo : Entity
    {
        public int TransformacionCampoId { get; set; }
        public int CampoDestinoId { get; set; }
        public int MensajeDestinoId { get; set; }
        public Nullable<int> CampoOrigenId { get; set; }
        public Nullable<int> MensajeOrigenId { get; set; }
        public Nullable<int> PosicionInicial { get; set; }
        public Nullable<int> Longitud { get; set; }
        public Nullable<int> Tipo { get; set; }
        public Nullable<int> TablaId { get; set; }
        public Nullable<int> ColumnaOrigenId { get; set; }
        public Nullable<int> ColumnaDestinoId { get; set; }

        public virtual TransformacionCampo TransformacionCampo { get; set; }
    }
}
