//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PasoDinamica
    {
        public int Id { get; set; }
        public int Funcionalidad { get; set; }
        public string Numero { get; set; }
        public bool Fin { get; set; }
        public int Paso { get; set; }
        public int MensajeTransaccionalId { get; set; }
        public Nullable<int> Reintentos { get; set; }
        public Nullable<int> EntidadComunicacionId { get; set; }
        public string InformacionAdicional { get; set; }
    
        public virtual EntidadComunicacion EntidadComunicacion { get; set; }
        public virtual MensajeTransaccional MensajeTransaccional { get; set; }
    }
}
