//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Protocolo
    {
        public Protocolo()
        {
            this.EntidadComunicacion = new HashSet<EntidadComunicacion>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> TimeoutRequest { get; set; }
        public Nullable<int> TimeoutResponse { get; set; }
        public Nullable<int> Puerto { get; set; }
        public string Componente { get; set; }
        public string Clase { get; set; }
        public string Metodo { get; set; }
        public Nullable<int> TipoComunicacionId { get; set; }
        public Nullable<bool> IniciaComunicacion { get; set; }
        public Nullable<bool> AceptaComunicacion { get; set; }
        public Nullable<int> Frame { get; set; }
        public string CaracterInicio { get; set; }
        public string CaracterFin { get; set; }
    
        public virtual ICollection<EntidadComunicacion> EntidadComunicacion { get; set; }
        public virtual TipoComunicacion TipoComunicacion { get; set; }
    }
}
