//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntity
{
    using System;
    using System.Collections.Generic;

    public partial class PuntoServicio : Entity
    {
        public PuntoServicio()
        {
            this.Terminales = new HashSet<Terminal>();
        }

        public string Nombre { get; set; }
        public bool Estado { get; set; }
        public string Direccion { get; set; }

        public virtual ICollection<Terminal> Terminales { get; set; }
    }
}
