//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReglaMensajeTransaccional
    {
        public int Id { get; set; }
        public Nullable<int> PosicionInicial { get; set; }
        public Nullable<int> Longitud { get; set; }
        public string Valor { get; set; }
        public int CampoId { get; set; }
        public int MensajeId { get; set; }
        public int MensajeTransaccionalId { get; set; }
    
        public virtual MensajeTransaccional MensajeTransaccional { get; set; }
    }
}
