//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntity
{
    using System;

    public class Terminal : Entity
    {
        public string Serial { get; set; }
        public DateTime? FechaRegistro { get; set; }
        public int? EstadoTerminalId { get; set; }
        public int? PuntoServicioId { get; set; }
        public int? EntidadComunicacionId { get; set; }

        public virtual EstadoTerminal EstadoTerminal { get; set; }
        public virtual EntidadComunicacion EntidadComunicacion { get; set; }
        public virtual PuntoServicio PuntoServicio { get; set; }
    }
}
