//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoDato
    {
        public TipoDato()
        {
            this.Campo = new HashSet<Campo>();
            this.CampoPlantilla = new HashSet<CampoPlantilla>();
        }
    
        public int Id { get; set; }
        public string Descripcion { get; set; }
        public string Nombre { get; set; }
    
        public virtual ICollection<Campo> Campo { get; set; }
        public virtual ICollection<CampoPlantilla> CampoPlantilla { get; set; }
    }
}
