//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransformacionCampo
    {
        public TransformacionCampo()
        {
            this.ParametroTransformacionCampo = new HashSet<ParametroTransformacionCampo>();
        }
    
        public int Id { get; set; }
        public int CampoDestinoId { get; set; }
        public int MensajeDestinoId { get; set; }
        public string Componente { get; set; }
        public string Clase { get; set; }
        public string Metodo { get; set; }
        public string Procedimiento { get; set; }
        public string ValorConstante { get; set; }
        public Nullable<int> FuncionalidadEstandar { get; set; }
        public int Tipo { get; set; }
        public Nullable<int> TransformacionId { get; set; }
    
        public virtual ICollection<ParametroTransformacionCampo> ParametroTransformacionCampo { get; set; }
        public virtual Transformacion Transformacion { get; set; }
    }
}
