//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessEntity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transformacion
    {
        public Transformacion()
        {
            this.TransformacionCampo = new HashSet<TransformacionCampo>();
        }
    
        public int Id { get; set; }
        public string Nombre { get; set; }
        public int MensajeOrigenId { get; set; }
        public int MensajeDestinoId { get; set; }
    
        public virtual Mensaje Mensaje { get; set; }
        public virtual Mensaje Mensaje1 { get; set; }
        public virtual ICollection<TransformacionCampo> TransformacionCampo { get; set; }
    }
}
