
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>


namespace BusinessEntity
{
    using System;
    using System.Collections.Generic;
    
    public class CondicionMensaje:Entity
    {
        public CondicionMensaje()
        {
            this.MensajeTransaccional = new HashSet<MensajeTransaccional>();
        }
    
        public string Nombre { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<MensajeTransaccional> MensajeTransaccional { get; set; }
    }
}
