
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>


namespace BusinessEntity
{
    using System.Collections.Generic;
    
    public class GrupoValidacion:Entity
    {
        public GrupoValidacion()
        {
            this.ValidacionCampo = new HashSet<ValidacionCampo>();
        }
    
        public string Nombre { get; set; }
        public int MensajeId { get; set; }
    
        public virtual Mensaje Mensaje { get; set; }
        public virtual ICollection<ValidacionCampo> ValidacionCampo { get; set; }
    }
}
